global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'linkerd'
  metrics_path: /admin/metrics/prometheus

  consul_sd_configs:
    - server:   '172.17.0.1:8500'

  relabel_configs:
  # only collect from linkerd's
  - source_labels: ['__meta_consul_service']
    regex:         (.*(9990)$)
    action: keep
  # strip off port
  - source_labels: ['__meta_consul_service']
    action: replace
    target_label: instance
    regex: (.*)-9990
    replacement: $1

  metric_relabel_configs:
  # remove port postfix from consul auto-naming
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:outgoing:dst:id:_:io_l5d_consul:dc1:([^:]+)_4140:(.*)
    replacement:   rt:outgoing:dst:id:_:io_l5d_consul:dc1:$1:$2
  # write service names into label {service:"app1"}
  # rt:outgoing:dst:id:_:io_l5d_consul:dc1:forex_exchange_rate:requests
  - source_labels: [__name__]
    action:        replace
    target_label:  service
    regex:         rt:outgoing:dst:id:_:io_l5d_consul:dc1:([^:]+):.*
    replacement:   $1
  # write service names into label {service:"app1"}
  # rt:incoming_forex_currency_converter:dst:id:_:inet:127_1:80:requests
  - source_labels: [__name__]
    action:        replace
    target_label:  service
    regex:         rt:incoming_(.+):dst:id:_:inet:127_1:80.*
    replacement:   $1
  # remove service name from metric (linkerd:outgoing:requests)
  # rt:outgoing:dst:id:_:io_l5d_consul:dc1:forex_exchange_rate:requests
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:outgoing:dst:id:_:io_l5d_consul:dc1:[^:]+:(.*)
    replacement:   linkerd:outgoing:$1
  # remove service name from metric (linkerd:incoming:requests)
  # rt:incoming_forex_currency_converter:dst:id:_:inet:127_1:80:requests
  - source_labels: [__name__]
    action:        replace
    target_label:  __name__
    regex:         rt:incoming_(.+):dst:id:_:inet:127_1:80:(.*)
    replacement:   linkerd:incoming:$2
